package io.baselines.sample.compose.di

import me.tatarka.inject.annotations.Component
import software.amazon.lastmile.kotlin.inject.anvil.AppScope
import software.amazon.lastmile.kotlin.inject.anvil.MergeComponent
import software.amazon.lastmile.kotlin.inject.anvil.SingleIn

@MergeComponent(AppScope::class)
@SingleIn(AppScope::class)
abstract class IosAppComponent(
    @Component override val platformComponent: IosPlatformComponent
) : AppComponent {

    abstract val uiComponentFactory: IosUiComponent.Factory

    companion object
}

// Suppressing the error, function is generated by KSP
@Suppress("NO_ACTUAL_FOR_EXPECT")
@MergeComponent.CreateComponent
expect fun createAppComponent(platformComponent: IosPlatformComponent): IosAppComponent
